@Library('shared-library') _

pipeline {
    agent any

    environment {
        ECR_REGISTRY = "317492542025.dkr.ecr.us-east-1.amazonaws.com"
        IMAGE_NAME = "317492542025.dkr.ecr.us-east-1.amazonaws.com/clouddevops-repo"
        IMAGE_TAG = "${BUILD_NUMBER}"
        REPO_URL = "https://github.com/momagdyy/CloudDevOpsProject.git"
    }

    stages {
        stage('Build Image') {
            steps {
                dir('docker') {
                    buildImage(IMAGE_NAME, IMAGE_TAG)
                }
            }
        }

        stage('Scan Image') {
            steps {
                scanImage(IMAGE_NAME, IMAGE_TAG)
            }
        }

        stage('Push Image') {
            steps {
                sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                pushImage(IMAGE_NAME, IMAGE_TAG)
            }
        }

        stage('Delete Image Locally') {
            steps {
                removeImage(IMAGE_NAME, IMAGE_TAG)
            }
        }

        stage('Update Manifests') {
            steps {
                updateManifests(IMAGE_NAME, IMAGE_TAG)
            }
        }

        stage('Push Manifests') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    pushManifests("https://momagdyy:${GITHUB_TOKEN}@github.com/momagdyy/CloudDevOpsProject.git", IMAGE_TAG)
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished!'
            sh 'docker logout'
        }
        success {
            echo 'Pipeline succeeded! ✅'
        }
        failure {
            echo 'Pipeline failed! ❌'
        }
    }
}