---
- name: Configure Jenkins Server
  hosts: all
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/clouddevops-key.pem
  roles:
    - java
    - jenkins
    - docker
    - trivy
